name: flutter_fitness_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  iconly: ^1.0.1
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\img\1.jpg
    - assets\img\2.jpg
    - assets\img\3.jpg
    - assets\img\4.jpg
    - assets\img\dashbordbg.jpg
    - assets\img\dashbordbg.png
    - assets\img\proCover.jpg
    - assets\img\proIcon.jpg
    - assets\img\sp.png
